import { readFile, rename, writeFile, stat } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { validateLicenseRecords } from "./lib/license-validation";

interface FlSourceConfig { source: string; homepage: string; licensePrefixes: Record<string, string>; classificationTerms: Record<string, string[]>; headerAliases: Record<string, string[]>; activeStatusValues: string[]; maxRecords: number; }
type Row = Record<string, string>; type OutputRecord = Record<string, unknown>;
function parseCsv(text: string): string[][] { const rows: string[][] = []; let field = "", row: string[] = [], quoted = false; for (let i = 0; i < text.length; i++) { const c = text[i]; if (quoted) { if (c === '"' && text[i + 1] === '"') { field += '"'; i++; } else if (c === '"') quoted = false; else field += c; } else if (c === '"') quoted = true; else if (c === ",") { row.push(field); field = ""; } else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; } else if (c !== "\r") field += c; } if (field.length || row.length) { row.push(field); rows.push(row); } return rows.filter((r) => r.some((value) => value.trim())); }
const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
function asRows(text: string): Row[] { const raw = parseCsv(text); if (!raw.length) return []; const headers = raw[0].map((h) => h.trim().toLowerCase()); const hasHeader = headers.some((h) => ["license number", "license nbr", "license", "license type"].includes(h)); return hasHeader ? raw.slice(1).map((r) => Object.fromEntries(headers.map((h, i) => [h, (r[i] ?? "").trim()]))) : raw.map((r) => Object.fromEntries(r.map((value, i) => [`column${i + 1}`, value.trim()]))); }
function resolveField(config: FlSourceConfig, field: keyof FlSourceConfig["headerAliases"], headers: string[]): string | null { const aliases = (config.headerAliases[field] ?? []).map(norm); return headers.find((header) => aliases.includes(norm(header))) ?? null; }
function normalizeDate(value: string): string | undefined { if (!value) return undefined; const mdy = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.exec(value.trim()); const dmy = /^(\d{1,2})-([A-Za-z]{3})-(\d{2})$/.exec(value.trim()); const candidate = mdy ? `${mdy[3]}-${mdy[1].padStart(2, "0")}-${mdy[2].padStart(2, "0")}` : dmy ? `${dmy[1]}-${dmy[2]}-20${dmy[3]}` : value; return Number.isNaN(Date.parse(candidate)) ? undefined : new Date(candidate).toISOString().slice(0, 10); }
function cityOnly(value: string): string | undefined { return value ? value.replace(/\s+[A-Z]{2}\s+\d{5}(?:-\d{4})?$/i, "").replace(/,\s*$/, "").trim() || undefined : undefined; }
async function recordsFromFile(config: FlSourceConfig, file: string, seen: Set<string>): Promise<OutputRecord[]> { if ((await stat(file)).size === 0) return []; const rows = asRows(await readFile(file, "utf8")); if (!rows.length) return []; const headers = Object.keys(rows[0]); const headerless = headers.every((header) => header.startsWith("column")); const columns = headerless ? { licenseNumber: "column21", businessName: "column3", classification: "column2", status: "column15", issuedAt: "column16", expiresAt: "column18", county: "column10", city: "column9" } : { licenseNumber: resolveField(config, "licenseNumber", headers), businessName: resolveField(config, "businessName", headers), classification: resolveField(config, "classification", headers), status: resolveField(config, "status", headers), issuedAt: resolveField(config, "issuedAt", headers), expiresAt: resolveField(config, "expiresAt", headers), county: resolveField(config, "county", headers), city: resolveField(config, "city", headers) }; if (!columns.licenseNumber || !columns.businessName) throw new Error(`Could not map required columns in ${file}: ${headers.join(", ")}`); const output: OutputRecord[] = []; for (const row of rows) { const licenseNumber = row[columns.licenseNumber]; const businessName = row[columns.businessName]?.trim(); const classification = columns.classification ? row[columns.classification] ?? "" : ""; if (!licenseNumber || !businessName) continue; const prefix = Object.entries(config.licensePrefixes).find(([candidate]) => norm(licenseNumber).startsWith(norm(candidate))); const classificationMatch = Object.entries(config.classificationTerms).find(([, terms]) => terms.some((term) => norm(classification).includes(norm(term)))); const trade = prefix?.[1] ?? classificationMatch?.[0]; if (!trade) continue; const idKey = norm(licenseNumber); if (!idKey || seen.has(idKey)) continue; seen.add(idKey); const rawStatus = columns.status ? row[columns.status].trim().toLowerCase() : ""; // DBPR CSV column 15: "A" = active, "I" = inactive. The activeStatusValues from config handle named statuses; for the headerless CILB CSV we map the single-letter code directly. const active = config.activeStatusValues.some((value) => rawStatus === value || rawStatus.includes(value)) || (headerless && rawStatus === "a"); output.push({ id: `fl-${idKey}`, stateCode: "FL", licenseNumber, businessName, trade, classification: classification || undefined, status: active ? "active" : rawStatus === "i" ? "inactive" : rawStatus || "unknown", issuedAt: columns.issuedAt ? normalizeDate(row[columns.issuedAt]) : undefined, expiresAt: columns.expiresAt ? normalizeDate(row[columns.expiresAt]) : undefined, county: columns.county ? row[columns.county] && row[columns.county] !== "FL" ? row[columns.county] : undefined : undefined, city: columns.city ? cityOnly(row[columns.city]) : undefined, sample: false }); if (output.length >= config.maxRecords) break; } return output; }
async function main() { const config = JSON.parse(await readFile(join(process.cwd(), "data", "sources", "licenses-fl.json"), "utf8")) as FlSourceConfig; const sourceFile = process.env.FL_LICENSE_DATA_FILE || join(process.cwd(), "Data files", "CONSTRUCTIONLICENSE_1.csv"); const records = await recordsFromFile(config, sourceFile, new Set()); if (!records.length) throw new Error(`No supported Florida contractor records found in ${sourceFile}`); const validation = validateLicenseRecords(records, "FL"); if (!validation.valid) throw new Error(`Dataset validation failed: ${validation.errors.join(" ")}`); const target = join(process.cwd(), "data", "licenses", "fl.json"); const temp = `${target}.tmp`; await writeFile(temp, JSON.stringify({ meta: { source: config.source, sourceUrls: ["https://www2.myfloridalicense.com/construction-industry/public-records/", sourceFile], retrievedAt: new Date().toISOString(), count: records.length }, records }, null, 2)); await rename(temp, target); console.log(`Validated and wrote ${records.length} FL contractor records.`); }
main().catch((error) => { console.error("[licenses-fl] FAILED; existing data left untouched.", error instanceof Error ? error.message : error); process.exitCode = 1; });
